- code/game/objects/items/weapons/storage/belt.dm
- code/modules/jobs/job_types/security.dm
:cl: Pascal125
tweak: Modifies Security Belts to be capable of storing Miniature Energy Guns.
tweak: Replaces the starting Stetchkin with Miniature Energy Guns.
(Hopefully there should be no parsing errors.)
/:cl:
> Modular Energy Guns

- code/controllers/subsystem/starmap.dm
:cl:
Obsessive Compulsive Disorder. That is all.
/:cl:
> Very Minor Spelling Fix

- code/controllers/subsystem/starmap.dm
tweak: The 'ftl/gohome' objective now is called after 2h 15'00", up from 1h 30'00".
/:cl:
135 minute sessions minimum, instead of 90.
> changes the 'go home' thing to 2h 15'00" from 1h 30'00"

- _maps/map_files/SpaceSHIP.dmm
- _maps/map_files/SpaceSHIP/SpaceSHIP.dmm
:cl:Pascal125
Replaces Schrodinger from the bridge with Faster-Than-Lizard (13). Our lovable mascot. 
Adds description to Faster-Than-Lizard (13) "That's Faster-Than-Lizard (13). The Shuttle's lovable Mascot... Eats those pesky cockroaches, too. Bonus!"
Adds an Autodrobe and Clothesmate to the Sleep Room, replacing two Personal Lockers.
Adds an Athletic mixed locker to the EVA Hangar.
Adds an extra Tranquilizer Magazine to the Armory for the Sniper Rifle
Adds a Light Replacer to the table in the Engineering Foyer and Custodial Closet
Added two racks to the "Mining Equipment" room. One containing three Hardsuit Jetpack upgrades, the other containing Three Magboots.
Adds a Grille and Catwalk combination to the space outside of the bridge, indicating the potential weapons area's of the ships …
> Small SpaceSHIP Map Changes

- _maps/map_files/SpaceSHIP/SpaceSHIP.dmm
:cl: Hits
add: 2 tube-lights, 1 in hallway north of tool storage, 1 inside tool storage.
del: Removed light replacer from the engineering storage/meeting room, there is a rack with 3 of them in the engineering airlock
tweak: compacted engineering storage/meeting, used space to make gravity generator room. note, aside from the missing light replacer, everything is still there, just made more compact, with 1 exception, the tank dispenser is now located in the engineering airlock.
tweak: moved gravity generator to new room, moved ftl drive from shared room to old grav-gen room
tweak: shortened the width of the now shield generator only room, enabling the engineering hallway to be 2-tiles-wide.
tweak: the blast doors of the engineering airlock have been re-designed, to accomadate the new …
> putin's pride

- code/modules/power/cell.dm
- code/modules/power/phase_cannon.dm
Cell charge is doubled of their base capacity.
Phase cannons use double their old shot charge.
Phase cannons' charge per shot is now also a variable.
tweak: nerfed the power nerf by 80%
/:cl:
> Power nerf nerf

- code/game/machinery/doors/firedoor.dm
del: Removes safety check from firelocks
/:cl:
Theoretically should cause firelocks to close over the windows, but I don't know well it'd work in practice (if at all)
> Removes safety check from firelocks

- _maps/map_files/Trailblazer/Trailblazer.dmm
add: adds missing fire alarms to several areas.
add: adds missing firelocks to munitions and R&D
add: adds signs pointing to most of the departments
add: medbay and genetics have exit buttons now
add: Faster-Than-Lizard(13) has signed up as Lizard.
add: Added a small fan to the phase cannon accessway to reduce space wind.
del: Fired the other cleaner. Most vents now have glowing goo near them.
del: Fired the exterminator. 
tweak: redid the vast majority of the ship's lighting to be moodier. A LOT moodier.
tweak: redid most, if not all, status displays to be visible through one wall only. (There are some exceptions.)
tweak: Replaced some grilles with broken grilles. According to the code.
fix: fixed a fire alarm in sec that had too high an offset value
fix: Fixed …
> Another Basilisk update

- _maps/map_files/Trailblazer/Trailblazer.dmm
add: The Armoury now spawns four BR55-CV rifles plus four magazines, in place of the fragmentation grenades that were there.
add: Added a few more small firelocks, notably to medbay cryo, AI upload, munitions office. Reworked brig cell firelocks.
tweak: Moved the whole of Cargonia four units to the right so the dock port conveyor would line up. Mining's podbay now has an extra parking space, and an entry foyer. Wew.
/:cl:
> Trailblazer update - 2017.02.06

- _maps/map_files/Trailblazer/z2.dmm
add: Added a lot of area to Centcomm, for RP memery or whatever.
/:cl:
Detailed changelog:
* Added an operations room to the Centcomm area, containing consoles for monitoring the ship (akin to the bridge on Matastation)
* Added offices for memery
* Currently there are three offices mapped out: Andrea Kelloway's, Andreas Spitzer's, and Richard Dunn's. (Richard Dunn is my Centcomm meme guy)
* Added a pod bay
* The pod bay has four hangars, with three security pods and an empty one on the far end.
* Each pod bay has a jimmy to get the spacepod door lock out, a blank key so you can lock it, and a GPS so you can find the coordinates to get back to Centcomm.
* Added a security checkpoint.
* The security checkpoint acts like the Virology entry airlocks, except controlled by …
> Updates Z2

- code/game/objects/items/weapons/storage/storage.dm
- code/modules/clothing/spacesuits/hardsuit.dm
:cl: hits
fix: storage items now properly update. injecting blood into a stack of grey slime extracts in a bio-bag now doesnt result in the rest of the extracts not being shown.
skub: skub
tweak: captain's hardsuit is now fire immune, this should have been immune when you ported the change, betrays.
/:cl:
> part two of xenobio fixings

- code/game/gamemodes/objective.dm
tweak: Pirates are now less of a threat to Nanotrasen.
/:cl:
Reduces chance to get a "destroy pirates" objective to 5%, down from 25%. You get told to kill 1 to 3 pirate ships, down from 5 to 10.
Pirates tend to get wiped out pretty early with the slow rate we play at, so giving them a lower chance to be the target is beneficial to the ship as a whole when you're doing objectives. ***Thoughts on this change are welcomed.***
At some point we do need to get back to doing objectives rather than doing ERP all day. I'll resume work on the cab-forward Astraeus variant in the meantime.
> nerfs percent chance to get a 'kill pirates' objective

- code/controllers/subsystem/starmap.dm
- config/admins.txt
tweak: Reduces default target round time to 2h 30:00. Admins can varedit it to be longer if needed.
/:cl:
> Reduces round time

- _maps/map_files/Trailblazer/Trailblazer.dmm
add: Added missing spawnpoints, including observer spawn.
add: Added a nuclear authentication diskette. Secure dat fukken disk,
tweak: Tweaked thrusters, due to new 96x sprites. There are now 3 FTL thrusters and 4 manoeuvring thrusters per side.
tweak: Renamed locker room doors to "Locker Room". In case it wasn't obvious enough.
fix: Fixed AI core scrubber. It was missing a pipe.
/:cl:
Nuke disk spawns in Cap's office because I'm an unrobust fucker.
> Basilisk updates

- code/game/machinery/firealarm.dm
fix: Fire alarms should now trigger properly if it's too cold.
/:cl:
Fire alarms are set to trigger at -15 Celsius. I could make the high-temp trigger more sensitive if need be.
> Fire Alarm Update 2

- code/controllers/subsystem/ships.dm
fix: Removes planetary check from ship disengagement code.
/:cl:
[10:21] Marshall Bash: I'm on my own solo server, breaking another ship in a solo run to hone my skills.
[10:22] Marshall Bash: ...But they keep disengaging, then reengaging repeatedly if they're not on the same planet for some reason.
> Removes planetary check from ship disengagement code

- _maps/map_files/Trailblazer/Trailblazer.dmm
add: The NCV Basilisk now has a cleaner again - areas Jonas has repeatedly cleaned now have a lot less round-start detritis.
add: Added Jonas' entire dossier to the vault filing cabinet. All 14 pages. Ree.
add: Added floor tiles to custodial.
add: Re-added lightbulbs in the halls where the bulb assembly was partially deconned.
add: Added a sink to the custodial closet.
fix: Jonas has been fixing parts of the ship up.
/:cl:
The IC justification is that Jonas is permitted to do maintenance while the Basilsik is at drydock (albeit heavily watched), so areas he can access are getting cared for as part of his effort to repay his debt to the ship.
> The Trailblazer now has a cleaner again

- _maps/map_files/Trailblazer/Trailblazer.dmm
- _maps/map_files/Trailblazer/z2.dmm
- _maps/ship_encounters/station.dmm
- _maps/ship_encounters/station2.dmm
:cl: hits
tweak: engineering auxiliary room is now engine crate storage room
add: crates containing various components for each available engine type are now stored in the room, sans solars, due to their nature.
skub: skub
fix: unborked rob's locker, and tried a new approach to the custom pistol, lets hope this one works.
del: most of the main engine room, sans mass driver, blast doors, TEG, power distro and smes area, generic coolant tanks, and mass driver controls.
tweak: moved TEG to the south-west side of engine room to get it out of the way, and near-er the cooling loop
tweak: moved SM mass driver and blast door controls to the southwest wall of engineering, so you can still eject the SM shard.
/:cl:
add: Fixed dossier.
tweak: Z2 updates for Kelloway.
:cl: Pascal …
> Basilisk updates... again

- _maps/map_files/Trailblazer/Trailblazer.dmm
- config/admins.txt
- config/config.txt
- config/game_options.txt
:cl: bored hits
add: proper light in engineering storage
tweak: moved anesthetic locker to medbay storage
del: one of the medical doctor's lockers, replaced with anesthetic locker listed above
add: table to surgery room
tweak: move IV to tile that is 1 space north of bloodbag crate, where anesthetic locker used to be
tweak: moved roughly half of the surgical tools to the new table
add: chain of command
add: 20 plasteel to engineering materials crate
tweak: changed 20 high-capacity rcd matter packs to 30 normal sized ones, a nerf, yes, but the high-capacity ones could only be used if the RCD was totally out of matter, which if you got stuck at 1 or 2 or 3 units left, you're screwed!
fix: mis-designated area near FTL
fix: disposals pipe system near cargo.... god that was one helluva mess …
> Basilisk update number I don't even know at this point

- code/game/machinery/autolathe.dm
- code/game/machinery/porta_turret/portable_turret.dm
- code/game/mecha/equipment/weapons/weapons.dm
- code/modules/mob/living/simple_animal/hostile/syndicate.dm
- code/modules/projectiles/ammunition.dm
- code/modules/projectiles/ammunition/ammo_casings.dm
- code/modules/projectiles/ammunition/boxes.dm
- code/modules/projectiles/ammunition/magazines.dm
- code/modules/projectiles/ammunition/special.dm
- code/modules/projectiles/gun.dm
- code/modules/projectiles/guns/projectile.dm
- code/modules/projectiles/guns/projectile/automatic.dm
- code/modules/projectiles/guns/projectile/pistol.dm
- code/modules/projectiles/projectile.dm
- code/modules/projectiles/projectile/bullets.dm
- code/modules/research/designs/autolathe_designs.dm
Poll: http://www.strawpoll.me/12411902
wip: Adds damage spread.
/:cl:
---
---
* ~~Redo bullets~~ 5316804
* ~~Set ammo casing code to use updated bullets~~ e4dd88b
* ~~Add HP/AP ammo types, which are worse than regular ammo in the wrong situation but better in the right situation~~ 5316804
* HP, which will be labelled JHP (**j**acketed **h**ollow**p**oint) for handguns and SpHP (**Sp**itzer **h**ollow**p**oint) for rifles in game, has a higher base damage, but increases the base armour of the target more than the base damage is increased.
* AP, which will be labelled HVAP (**h**igh-**v**elocity **a**rmour-**p**iercing) for handguns and AP-T (**a**rmour-**p**iercing **t**racer) for rifles in-game, has a lower base damage, but decreases the base armour of the target more …
> Gun revamp

- _maps/map_files/Trailblazer/Trailblazer.dmm
add: Adds centcomm and AI holopads to bridge area. Adds AI holopad to AI chamber.
add: Added missing air alarm in janitorial closet, abandoned office, and Chemistry. Added an air system to TComms in the event it gets hit and needs a refill.
add: Added a missing plating near the vault.
add: Added scrubbers and a few more vents to Medbay proper.
add: Added a master atmospheric tank monitor to Atmosia, so Atmosians can look and see how much N2 and O2 they have left without moving from console to console.
del: Removed errant turret control outside the AI chamber.
tweak: Partially reverted airmix update: Instead of N2 and 20/80 starting at 600 MPa, now N2 and O2 start at 600 MPa. This is to allow for players to set their own airmix instead of being forced into 20/80. (That …
> Updates Trailblazer

- .travis.yml
- _maps/map_files/nighthowler/nighthowler.dmm
- _maps/nighthowler.dm
add: Adds a "new" map, which is really just a cab-forward Astraeus with a couple of additions to reduce the wasted space.
wip: The new map is very much a work in progress.
/:cl:
**THIS HAS NOT BEEN TESTED YET. SORRY. I'M LAZY, OKAY?**
Adds a new ship, the Nanotrasen Assault Vessel (NAV) Nighthowler-class, to the list of ships the players can use. The Nighthowler-class is essentially a cab-forward Astraeus, but better-equipped. Compared to the Astraeus, the Nighthowler boasts a locker room, a fitness room, a lounge, and a proper 4-room dormitory. The cryosleep room now sports a changing room. And yes, there are request consoles now.
Uses the Trailblazer/Basilisk's z2.
The enginebay has been overhauled to start out like my standard engineering setup. **Some configuration …
> Adds a "new" map, the NAV Nighthowler, which is really just an extensive edit of the NSV Astraeus.

- code/modules/reagents/reagent_containers/pill.dm
:cl: hits
Fix: changed antitox pill name to charcoal.
/:cl:
It's fucking charcoal, not antitox. Don't make chemists think it's ok to dose people with more than 30u of antitox, or make people not use the pill in fear of overdosing.
> Fixes charcoal pill mis-labeling.
