Pascal125/Faster-Than-Lizard-13

config/admin_ranks.txt, config/admins.txt, config/config.txt, config/game_options.txt, config/motd.txt, config/silicon_laws.txt, config/sillytips.txt
:cl: Pascal125
tweak: Added our Admins to admins.txt.
tweak: Added Special Admin Ranks to admin_ranks.txt.
tweak: Modified config.txt to be more Compatible.
tweak: Modified game_options.txt to be more Compatible.
tweak: Snowflake-ified motd.txt.
tweak: Added in custom laws to silicon_laws.txt
tweak: Added an extra line to sillytips.txt
(Re PR'd for Travis CI)
/:cl:
=> Changes various Options and Settings in Config

_maps/ship_salvage/drone.dmm
:cl: Pascal123
Hopefully uploads working Salvage .dmm's to replace any possibly broken .dmm's
/:cl:
=> Hopefully Fixes Patrol Drone Salvage / Take Three

code/modules/mob/living/silicon/pai/pai_shell.dm
experiment: Added in code for a 3-stage pAI headlight. With error handling!
/:cl:
=> Add code for a 3-stage pAI headlight

code/modules/mob/living/silicon/pai/pai_shell.dm
=> remove error handling, hopefully fix slowdown

code/game/machinery/vending.dm, code/game/objects/items/weapons/storage/belt.dm, code/modules/cargo/packs.dm, code/modules/projectiles/guns/projectile/pistol.dm
add: Adds M45 MEU(SOC) pistols to cargo
/:cl:
=> Adds M45 MEU(SOC) to the thing 

code/modules/jobs/job_types/captain.dm
despite having access to two energy guns at roundstart already
add: captain gets a mini e-gun
/:cl:
=> captain now spawns with a mini egun

code/datums/action.dm, code/modules/client/preferences.dm, code/modules/mob/new_player/preferences_setup.dm, code/modules/shuttle/emergency.dm
:cl:Pascal125
Just a few missing direct commits from FTL13 that addresses issues related to lag and such.
/:cl:
=> Tweaks from ftl13

cfg/admin.txt
:cl:Pascal125
Shameless power grab and revision.
/:cl:
=> Gives me profile access

_maps/map_files/SpaceSHIP/SpaceSHIP.dmm, code/game/objects/items/weapons/storage/bags.dm, code/modules/research/xenobiology/xenobio_camera.dm
:cl: Hits
add: ported xenobio qol from /tg/ enabling use of bio-bags to pickup monkey cubes and put them in the console.
fix: during earlier PR's i forgot to replace the plasma canisters, in exchange for a arguably better engineering dept, i have added back in empty canisters to be filled in their place.
fix: replaced the r-glass which the apc outside the aux construction room was sitting on with a r-wall... it couldnt be access when it was under the glass.
/:cl:
multifix/qol improvement.
=> crimea river

_maps/map_files/SpaceSHIP/SpaceSHIP.dmm
:cl: hits
fix: redefined gravity generator room, to enable transport with the rest of the ship
/:cl:
=> stalin pieces of mah ship

_maps/map_files/SpaceSHIP/SpaceSHIP.dmm
🆑 Hits
fix: ftl drive now charges
/:cl:
i didnt see that the ftl drive used a terminal (like apcs and smes) and instead thought it worked like emitters (powered cable knot underneath) as a result, it didnt recieve power.
=> chernobyl REDEUX

config/admin_ranks.txt, config/admins.txt, config/config.txt, config/game_options.txt, config/motd.txt
:cl: Pascal125
Just edits the config's admin ranks, admins, and options.
/:cl:
=> Minor edits to config

config/admin_ranks.txt, config/admins.txt, config/config.txt, config/game_options.txt, config/motd.txt
Reverts Pascal125/Faster-Than-Lizard-13#34
=> Revert "Minor edits to config"

config/admin_ranks.txt, config/admins.txt, config/config.txt, config/game_options.txt, config/motd.txt
Reverts Pascal125/Faster-Than-Lizard-13#35
=> Revert "Revert "Minor edits to config""

_maps/map_files/SpaceSHIP/SpaceSHIP.dmm
🆑 Hits
add: holodeck room
add: holodeck control room
tweak: shrinked eva to include bare essentials
add: eva auxiliary room, north of eva, containing stuff like the showers, banners, portable tcomms, etc.
/:cl:
=> The latest in vodka-based teknowledgy

code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/human_defense.dm
i am going to shit my fuck if this goes to ftl13, swear on me mum
tweak: vore
/:cl:
Feel free to reject, only really did it for Haylee.
=> The vore update

_maps/map_files/SpaceSHIP/SpaceSHIP.dmm
:cl:hits
fix: bathroom
tweak: armory
tweak: cargo/sec autolathe metal
tweak: autodrobe fix
tweak: tweak
tweak: sammiches
tweak: BLOOD FOR THE MATEBA GOD!!!
/:cl:
=> 	SUPER-SONIC... ELECTRONIC... IS MADE POSSIBLE WITH POWER OF UKRAINIAN INTEGRATION

_maps/map_files/SpaceSHIP/SpaceSHIP.dmm
:cl:hits
fix: holodek was too long for simulations to work... shortened.
/:cl:
=> UKRAINE TOO STRONK, NEEDS CUTTING DOWN

code/game/machinery/mac_cannon.dm
:cl: eviljackcarver
fix: mac sprite fix
/:cl:
how the `fsck` did i not notice that when i was trying to fix it
=> Fixes the MAC

config/admins.txt
:cl: Pascal125
As the name implies.
/:cl:
=> Adds Torsion to the Admin Text

_maps/map_files/SpaceSHIP/z2.dmm, _maps/map_files/Trailblazer/z2.dmm
=> Quite a bit of stuff.

_maps/map_files/SpaceSHIP/z2.dmm, _maps/map_files/Trailblazer/z2.dmm, code/controllers/subsystem/events.dm, code/game/area/Space_Station_13_areas.dm, code/game/turfs/simulated/dirtystation.dm, code/modules/holodeck/areas.dm, code/modules/holodeck/computer.dm
=> FTLifies Area's

_maps/map_files/SpaceSHIP/SpaceSHIP.dmm, _maps/map_files/SpaceSHIP/z2.dmm, _maps/map_files/Trailblazer/z2.dmm, code/controllers/subsystem/events.dm, code/game/area/Space_Station_13_areas.dm, code/game/turfs/simulated/dirtystation.dm, code/modules/holodeck/areas.dm, code/modules/holodeck/computer.dm
:cl: Pascal125
Fixes https://github.com/Pascal125/Faster-Than-Lizard-13/issues/41
/:cl:
=> Allows the shuttle to translocate Holodecks properly.

code/modules/client/preferences.dm, code/modules/events/ion_storm.dm, code/modules/events/meateor_wave.dm, code/modules/events/meteor_wave.dm
:cl: Pascal125
tweak: Raised the maximum character slots from three to ten.
tweak: Changed references from "Station" to "Shuttle".
/:cl:
=> Assorted tweaks

_maps/map_files/SpaceSHIP/SpaceSHIP.dmm
:cl:hits
add: lights to the eva hanger
add: windows to the holodeck so the lights can shine in without getting removed by the holodeck's functions
fix: removed access restrictions to autodrobe.
/:cl:
=> LENIN'S BURGERS ARE MADE FROM STRONK SOVIET COWS

_maps/map_files/SpaceSHIP/SpaceSHIP.dmm
:cl: hits
add: chem bags to chem
add: pill bottle box to chem
tweak: blood god is starting to feel annoyed by all this powergaming
fix: walls in robotics and atmo removed
/:cl:
=> SOVIET CHEMICAL PLANTS NEED DOORS, NOT WALLS, TO DRUG THE RED ARMY!

code/modules/research/designs.dm, code/modules/research/designs/stock_parts_designs.dm, code/modules/research/rdconsole.dm
tweak: the race director has issued a penalty to the protolathe for doing five times the pitlane speed limit
/:cl:
=> Stock lathe part speed update

_maps/map_files/SpaceSHIP/SpaceSHIP.dmm, code/modules/food_and_drinks/food/condiment.dm
🆑 HITS
add: light, in hallway south of sec, to fix lack of lighting.
tweak: tweak
tweak: re-design of entire kitchen.
tweak: sugar/rice/wheat containers now hold 100 units of their respective reagent.
/:cl:
=> YOU MUST EAT FOOD, TO BE STRONK SOLDIER FOR RED ARMY

_maps/map_files/SpaceSHIP/SpaceSHIP.dmm
:cl: hits
add: detective's flask, with snowflake text, as per request.
add: 3 emergency hull-breach shield projectors, for when there is a hull breach and you wanna shield from it.
/:cl:
=> DETECTIVE? WHO NEEDS DETECTIVE? SOVIET CONSCRIPTS JUST SHOOT OFFENDER!

code/controllers/subsystem/starmap.dm
:cl:Pascal125
More mission time.
/:cl:
=> Increases Mission Time

_maps/map_files/SpaceSHIP/SpaceSHIP.dmm
:cl: hits
add: 2 dorm rooms to the dorms section
del: all but 2 of the cryopods from the dorms
tweak: tweak
tweak: moved the ce's office to the grav-gen room
tweak: moved the grav-gen to the heat-exchange area
tweak: moved the heat-exchange pipes to the ce's office (previous location)
tweak: my mental stamina is too low now to actually map anything other then a rush-order bugfix. wait a few hours.
/:cl:
=> MAPPING THAT WAS WORSE THEN GOING FOR AN EXTENDED STAY VACATION TO MY LOCAL GULAG

_maps/map_files/SpaceSHIP/SpaceSHIP.dmm
:cl: hits
add: ai hologram projectors in the main rooms of all major depts, (sec, engineering, medbay, and rnd, plus the bar)
tweak: re-designed the bridge, according to proposal.
/:cl: hits
=> HOW CAN LENIN LEAD, WITHOUT PROPER KREMLIN?

code/modules/events/ion_storm.dm, code/modules/events/operative.dm, code/modules/events/radiation_storm.dm, code/modules/events/weightless.dm, code/modules/events/wormholes.dm, code/modules/shuttle/emergency.dm
:cl: Pascal125
More reference changes from "Station" to "Shuttle".
/:cl:
=> Few minor things

_maps/ship_salvage/Small_Freighter.dmm, _maps/ship_salvage/clanker.dmm, _maps/ship_salvage/drone.dmm, _maps/ship_salvage/large_freighter.dmm, _maps/ship_salvage/patrol_corvette.dmm, _maps/ship_salvage/ravager.dmm, _maps/ship_salvage/skirmisher.dmm, _maps/ship_salvage/sparrow_craft.dmm
:cl: hits
fix: directly ports the current ftl13 salvage maps
/:cl:
be ready to revert this if its broken. i fully expect it to be broken in some way...
=> ITS NOT STEALING... ITS RE-APPROPRIATION OR... SALVAGE! THE COMMUNISTIC WAY!

code/controllers/subsystem/starmap.dm
tweak: FTL jump time now scales based on distance, with a 65 second jump at 0 lightyears, and a 185 second jump at 20 lightyears.
/:cl:
=> FTL time refactor

code/controllers/subsystem/starmap.dm
i goofed it
fix: Fixes admin logging if the FTL system is in debug mode.
/:cl:
=> fix ingame logging

_maps/map_files/SpaceSHIP/SpaceSHIP.dmm
:cl: hits
del: personal closet outside of dorms
/:cl:
=> SLEEPING QUARTERS MUST BE UP TO SOVIET MUSTER FOR RED ARMY!!

code/modules/events/carp_migration.dm
cloaker noises
changelog still omitted
=> difficulty tweak part 2

_maps/map_files/SpaceSHIP/SpaceSHIP.dmm, code/modules/power/cell.dm, code/modules/power/phase_cannon.dm
:cl: hits
tweak:tweak
fix: bridge
fix: engineering, pipe shouldnt be there
tweak: cell buffed
tweak: phase cannon nerfed
fix: xenobio
=> not enough time to think up russian stuff

code/game/machinery/firealarm.dm
:cl: Pascal123
tweak:  Firealarms now go off if it's too cold
/:cl:
=> Firealarms go off if the room becomes too cold

code/controllers/subsystem/starmap.dm
Changelog omitted, as it's a change under the hood that players won't see under normal circumstances.
=> Makes the round time a var, so we can change it on the fly

_maps/map_files/SpaceSHIP/SpaceSHIP.dmm
:cl: hits
tweak: tweak
fix: fix
fix: ce's door
fix: bathroom's cameras.
/:cl:
#86 fixed, close when this is merged.
=> How can big brother watch over you, without proper cameras?

code/modules/cargo/packs.dm
you can now get a USP from stations
=> son of a fsck

code/controllers/subsystem/mapping.dm, code/controllers/subsystem/shuttles.dm, code/controllers/subsystem/starmap.dm, code/datums/planet_loader/planet_loader.dm, code/datums/stars.dm, code/modules/shuttle/ftl.dm
Ports https://github.com/FTL13/FTL13/pull/439
...sans planet icon stuff because that's not snowflakey enough, and power cell removals because I'm just a lazy bastard on that front.
=> Ftl13 starmap update port 2017.01.27

code/_compile_options.dm
this is going to either nerf the hunger rate by a factor of five or multiply it by a factor of five and i don't know which
tweak: adjusted hunger rate
/:cl:
=> adjust hunger rate

code/controllers/subsystem/mapping.dm, code/controllers/subsystem/shuttles.dm, code/controllers/subsystem/starmap.dm, code/datums/planet_loader/planet_loader.dm, code/datums/stars.dm, code/modules/shuttle/ftl.dm
Reverts Pascal125/Faster-Than-Lizard-13#92
=> Revert "Ftl13 starmap update port 2017.01.27"

code/_compile_options.dm
hunger is now half of what it originally was
=> adjust hunger rate 2 electric boogaloo

_maps/map_files/Trailblazer/Trailblazer.dmm
:cl: a stressed, annoyed, and angered hits
tweak:tweak
add: snowflake lockers and accompanying room
tweak: moved ai upload stuff to ai chamber, more turrets added to compensate.
add: new room, to act as a stop between the locker room, and the ai core. it contains the turret controller.
fix: cmo's door
fix: ssu underneath the blackbox
/:cl:
=> snowflakes, they melt eventually.

code/modules/events/vent_clog.dm
=> FUCK COCKROACHES

_maps/map_files/Trailblazer/Trailblazer.dmm
tweak: Trailblazer changes:
fix: Removed pods from the back end and edited evac shuttle to be flush with the outside wall. Ship SHOULD be able to dock now.
tweak: Moved AI core and locker room wall around to be able to fit five more lockers.
add: Added an autodrobe and a clothesmate to the locker room
fix: FTL drive and SM emitter should be wired at roundstart now.
fix: Added a cryo control computer so the cryopods actually work.
tweak: Replaced Stechkins in armoury with P12s.
/:cl:
=> updates trailblazer

code/game/objects/effects/spawners/lootdrop.dm
del: Removes pulse rifle from rare loot spawner
add: Said pulse rifle is now replaced with an emag
tweak: Reduced the spawner weight to 1 for the emag
/:cl:
=> Adds emag to salvage spawner

_maps/map_files/Trailblazer/Trailblazer.dmm
=> i goofed the firelock area at north medbay

code/controllers/subsystem/ships.dm
The ship mayday call chance is now a variable.
Changelog omitted: Players won't see the change under normal circumstances.
=> Variable-ises the ship mayday call chance.

_maps/map_files/Trailblazer/Trailblazer.dmm
also fixes #110
fix: miscellaneous locker room fixes
/:cl:
=> Locker room fixes

_maps/map_files/Trailblazer/Trailblazer.dmm, _maps/map_files/Trailblazer/z2.dmm, _maps/trailblazer.dm, code/game/objects/effects/spawners/lootdrop.dm
fix: Fixed an issue where the ship couldn't return to Z1 and thus would disintegrate on second FTL jump
add: Added a floor under the AI upload door, a fire alarm to Genetics, and an air alarm to the fore hall.
/:cl:
merges #112, fixes #113 and #114.
@Pascal125 high priority
=> Basilisk fixes 2017.02.03

_maps/map_files/Trailblazer/Trailblazer.dmm, code/game/objects/effects/spawners/lootdrop.dm
:cl: confused hits.
add: skub to conference room
tweak: tweak
tweak: re-design science
add: 1 more xenobio slime pen
add: firelocks to windows
tweak: re-design xenobio kill chamber
tweak: re-design "science dept" room, to be a more general purpose utility room. contains autolathe/pod fabricator/chemmaster/chem dispenser.
add: pill bottles and chem bags to chemistry.
add: bag of flour/flower to kitchen
/:cl:
=> SCI re-design. 

code/game/objects/items/weapons/defib.dm
soundadd: Defib unit beeps if you successfully refibrillate someone in cardiac arrest.
/:cl:
=> Defib unit now makes its happy beep if you refibrillate someone in cardiac arrest.

_maps/map_files/Trailblazer/Trailblazer.dmm
del: Fired the cleaner. The ship now has a lot more grime... many magnitudes more. Eeeugh.
del: Removed a few floor tiles in a bit of a logical pattern (some small rooms, and starting at the ends of the halls)
fix: Fixed access on Genetics monkey pen door
fix: Replaced bar tables with regular tables: Bar tables were designed for the bar shuttle and would fling off everyone who wasn't barstaff
add: There is now a CMC on the bridge.
add: Fire alarm systems have been expanded to cover the entire ship, sans cryosleep (not enough room there) and maintenance. The main halls' firelocks are designed for compartmentalisation in the event of a breach.
/:cl:
=> Update for 2017-02-04

code/modules/mob/living/simple_animal/hostile/megafauna/dragon.dm, code/modules/spells/spell_types/shapeshift.dm
=> Snowflake Inclusions

code/game/machinery/computer/arcade.dm, code/game/objects/effects/spawners/bombspawner.dm
:cl: hits
Fix: increased power from Cuban Pete's bombs
/:cl:
Fixes #127
=> Fixes outbomb Cuban pete.

code/modules/mob/living/simple_animal/hostile/megafauna/dragon.dm, code/modules/spells/spell_types/shapeshift.dm
=> Pascal125 patch 1

_maps/map_files/Trailblazer/Trailblazer.dmm
:cl: hits
tweak: moved chem bags to chem locker right outside of chem entrance door.
tweak: updated boris' snowflake locker. note, this is an update he requested last sunday, i just didnt map it in at the time due to him being the only person who requested an update. i will still keep to my sunday cycle, at least for a few more weeks
skub: skub
fix: firedoors in cargo.
/:cl:
=> kinda skubbing meh

code/controllers/subsystem/ships.dm, code/datums/ship.dm
Under-the-hood changes, so no proper changelog. The ship attack spam should hopefully be lessened.
=> Prepare the spammening

code/game/objects/items/stacks/sheets/glass.dm
fix: Code regarding stepping on glass shards now check if the mob is buckled to something.
/:cl:
=> Ev'rybody cut footloose!

_maps/map_files/Trailblazer/Trailblazer.dmm
:cl: hits
del: turret covers in ai core
skub: snowflake lockers updated
add: marshall's locker, dude, i am so sorry for forgetting that one.
/:cl:
=> improved freezers to keep the snowflakes cold.

_maps/map_files/Trailblazer/z2.dmm
add: Converted a dud office into one for Haylee Batten.
tweak: Anchored down the lockers in the security checkpoint.
tweak: Resized the confiscations room. 
tweak: Added a bit more litter to Andreas' office, to show how much of a trainwreck he's become.
/:cl:
=> centcomm day 3 fixes and additions

code/datums/stars.dm
FIXES THE FUCK OUT OF THE NOT_A_DOCKING_PORT ERROR, HOPEFULLY
=> SON OF A FUCK IT WAS THAT SIMPLE A FIX ALL ALONG

code/controllers/subsystem/ships.dm
tl;dr title
fixes #154, hopefully
=> Adds code to cause the ships to disengage on player FTL jumps

code/game/objects/structures/kitchen_spike.dm
Was going to port the TG fix for meatspike things being upside down but it's apparently already ported???
=> Eensy-weensy, tiny, insignificant grammar fix

code/modules/paperwork/folders.dm
Botched part of #165 
Speedmerge ahoy
=> YOU SAW NOTHING

_maps/map_files/Trailblazer/Trailblazer.dmm
:cl: Hits and Francis
fix: snowflake lockers... odd stuff
tweak: Adds more gas to the Airmix and N2 tanks.
add: redundant glass to airmix containment
add: redundent piping and wiring to the bridge, distro pipes only, waste pipes are not nearly as critical, so they arent redundantized.
add: wardrobes
add: manuals
add: redundant set of turret controls
del: redundants on escape shuttle
fix: door access for detective... i think. (PROLLY BORKED.)
/:cl:
also, #171 is now redundant. closing...
=> "my redundencies have redundancies..."

code/modules/power/phase_cannon.dm
tweak: Doing R&D on the phase cannon now actually does shit other than increasing the power capacity.
/:cl:
Better manip/laser == lower charge used per shot.
=> Phase cannon revamp

ftl13.dme
=> Compiler should now default to Trailblazer.

code/game/machinery/firealarm.dm
fix: Hopefully finally fixed the fire alarms not going off in too cold an environment.
add: Added a variable for later use to determine if the fire alarm is going off due to it being too hot or too cold.
/:cl:
=> FIRE ALARM COLD TRIGGER SHOULD BLOODY WORK NOW

code/modules/events/anomaly_pyro.dm, code/modules/events/brand_intelligence.dm, code/modules/events/carp_migration.dm, code/modules/events/communications_blackout.dm, code/modules/events/disease_outbreak.dm, code/modules/events/false_alarm.dm, code/modules/events/spider_infestation.dm
#74 revisited
Changelog intentionally omitted.
=> More random event difficulty tweaks

code/__DEFINES/tick.dm, code/controllers/configuration.dm, code/controllers/master.dm, code/controllers/subsystem/air.dm, code/controllers/subsystem/icon_smooth.dm, code/controllers/subsystem/jobs.dm, code/controllers/subsystem/lighting.dm, code/controllers/subsystem/minimap.dm, code/controllers/subsystem/ships.dm, code/controllers/subsystem/starmap.dm, code/controllers/subsystem/ticker.dm, code/datums/datacore.dm, code/datums/planet_loader/biome.dm, code/datums/planet_loader/earthlike.dm, code/datums/planet_loader/planet_loader.dm, code/datums/stars.dm, code/game/area/areas.dm, code/game/machinery/computer/crew.dm, code/game/machinery/ftl_drive.dm, code/game/machinery/ftl_shieldgen.dm, code/modules/lighting/lighting_system.dm, code/modules/mob/transform_procs.dm, code/modules/power/smes.dm, code/modules/ruins/lavaland_ruin_code.dm, code/modules/shuttle/shuttle.dm, code/modules/space_management/space_level.dm, code/modules/space_management/space_transition.dm, config/config.txt
too tired to changelog properly
codebase maintenance ports from ftl13
add shit, take shit out, i care not, i am going to bed now
- Deactivates Ash Storm.
- AI Ship message temporary fix
- New planet generator - Works fucking better
- Makes minimaps work (partial port!)
- Makes ftl and shields eject non-plasma gases and minor performance increase
- Fixes planet gravity and lighting
- changes "ETA" to "ETD" to be more accurate
- Potentially reduces lag at roundstart and roundend
- Possible ftl and shields fix
- Take 2 on fixing the shields and ftl
- Makes pirates spawn in neutral sectors other than in fleets 
- [SPEEDMERGE] The round will actually end now.
- Fixes runtime with SMES charged past capacity
=> Codebase maint 13 apr

_maps/map_files/Trailblazer/Trailblazer.dmm
:cl: hits
add: new snowflake lockers
add: cassie's locker back.
skub: skub
add: more resources to the kitchen
tweak: moved TEG up one tile, adjusted door to the left down one tile to counter.
/:cl:
=> THE SNOW FALLS TONIGHT IN LENINGRAD.

code/__HELPERS/text.dm
fix: fixed russian lowercase я by replacing it with uppercase Я. That isnt ideal, but it should do.
Also I just wanted to see if I can figure out how to PR.
=> Fix for a russian letter

config/admin_ranks.txt, config/admins.txt, config/motd.txt
@francinum's request
:cl: francis
tweak: motd.txt
tweak: admins.txt
tweak: admin_ranks.txt
/:cl:
=> UPDATE OF MOTD, ADMIN_RANKS, AND ADMINS.

code/modules/clothing/spacesuits/miscellaneous.dm
It doesn't work and I'm too damn lazy to fix it.
=> Removes the champion suit's brass variant.
